### ISSUE TITLE
 file not found /home/dmezzett/.codequestion/vectors/stackexchange-300d.magnitude

### ISSUE THREAD

**Issue by varilorant** [neuml/codequestion#9]
root@0497bd526f2b:/# codequestion
Loading model from /root/.codequestion/models/stackexchange
/usr/local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator TruncatedSVD from version 0.22.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/codequestion", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/codequestion/shell.py", line 35, in main
    Shell().cmdloop()
  File "/usr/local/lib/python3.8/cmd.py", line 105, in cmdloop
    self.preloop()
  File "/usr/local/lib/python3.8/site-packages/codequestion/shell.py", line 21, in preloop
    self.embeddings, self.db = Query.load()
  File "/usr/local/lib/python3.8/site-packages/codequestion/query.py", line 127, in load
    embeddings.load(path)
  File "/usr/local/lib/python3.8/site-packages/codequestion/embeddings.py", line 332, in load
    self.vectors = self.loadVectors(self.config["path"])
  File "/usr/local/lib/python3.8/site-packages/codequestion/embeddings.py", line 104, in loadVectors
    raise IOError(ENOENT, "Vector model file not found", path)
FileNotFoundError: [Errno 2] Vector model file not found: '/home/dmezzett/.codequestion/vectors/stackexchange-300d.magnitude'

**Comment by davidmezzetti** [comment]
Thank you for reporting the issue. It's being worked for the next release. For a workaround, see issue #2
